services:
  - services:
  - type: web
    name: it-project-planner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableXsrfProtection=false

